Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -223,9 +223,15 @@ jobs:
               ;;
           esac
           
-          cd ./kernel
+         if [ -d "$KSU_DIR/kernel" ]; then
+          cd "$KSU_DIR/kernel"
           KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" $BASE_VERSION)
+         else
+          echo "Error: Kernel directory for $KSU_DIR not found"
+          exit 1
+         fi
           echo "KernelSU version set to: $KSU_VERSION"
+          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
 
       - name: Apply SUSFS Patches for KernelSU Variants
         run: |
