Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -197,41 +197,43 @@ jobs:
               ;;
           esac
 
-      - name: Getting KernelSU Version
-        run: |
-          echo "Changing to configuration directory: $CONFIG..."
-          cd "$CONFIG"
-          
-          case "${{ inputs.kernelsu_variant }}" in
-            "WILD")
-              echo "Applying SUSFS patches for Official KernelSU..."
-              cd ./Wild_KSU
-              BASE_VERSION=10200
-              ;;
-            "KSU")
-              echo "Applying SUSFS patches for Official KernelSU..."
-              cd ./KernelSU
-              BASE_VERSION=10200
-              ;;
-            "NEXT")
-              cd ./KernelSU-Next
-              BASE_VERSION=10200
-              ;;
-            "MKSU")
-              cd ./KernelSU
-              BASE_VERSION=10200
-              ;;
-          esac
-          
-         if [ -d "$KSU_DIR/kernel" ]; then
-           cd "$KSU_DIR/kernel"
-           KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" $BASE_VERSION)
-          else
-           echo "Error: Kernel directory for $KSU_DIR not found"
-           exit 1
-         fi
-         echo "KernelSU version set to: $KSU_VERSION"
-         echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+-name: Getting KernelSU Version
+  run: |
+    echo "Changing to configuration directory: $CONFIG..."
+    cd "$CONFIG"
+    
+    case "${{ inputs.kernelsu_variant }}" in
+      "WILD")
+        KSU_DIR="Wild_KSU"
+        BASE_VERSION=10200
+        ;;
+      "KSU")
+        KSU_DIR="KernelSU"
+        BASE_VERSION=10200
+        ;;
+      "NEXT")
+        KSU_DIR="KernelSU-Next"
+        BASE_VERSION=10200
+        ;;
+      "MKSU")
+        KSU_DIR="KernelSU"
+        BASE_VERSION=10200
+        ;;
+      *)
+        echo "Unknown KernelSU variant: ${{ inputs.kernelsu_variant }}"
+        exit 1
+        ;;
+    esac
+    
+    if [ -d "$KSU_DIR/kernel" ]; then
+      cd "$KSU_DIR/kernel"
+      KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" $BASE_VERSION)
+    else
+      echo "Error: Kernel directory for $KSU_DIR not found"
+      exit 1
+    fi
+    echo "KernelSU version set to: $KSU_VERSION"
+    echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
 
       - name: Apply SUSFS Patches for KernelSU Variants
         run: |
