Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -248,26 +248,43 @@ jobs:
           
           case "${{ inputs.kernelsu_variant }}" in
             "WILD")
-              echo "Applying SUSFS patches for Official KernelSU..."
-              cd ./Wild_KSU
+              echo "Getting version for Wild KSU..."
+              KSU_DIR=./Wild_KSU
               BASE_VERSION=10200
               ;;
             "KSU")
-              echo "Applying SUSFS patches for Official KernelSU..."
-              cd ./KernelSU
+              echo "Getting version for Official KernelSU..."
+              KSU_DIR=./KernelSU
               BASE_VERSION=10200
               ;;
             "NEXT")
-              cd ./KernelSU-Next
+              echo "Getting version for KernelSU Next..."
+              KSU_DIR=./KernelSU-Next
               BASE_VERSION=10200
               ;;
             "MKSU")
+              echo "Getting version for MKSU..."
+              KSU_DIR=./KernelSU
+              BASE_VERSION=10200
+              ;;
+            *)
+              echo "Error: Invalid kernelsu_variant: ${{ inputs.kernelsu_variant }}"
+              exit 1
               ;;
           esac
           
-          cd ./kernel
-          KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" $BASE_VERSION)
-          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+          if [ -d "$KSU_DIR" ]; then
+            echo "Changing to KernelSU directory: $KSU_DIR..."
+            cd "$KSU_DIR"
+            COMMIT_COUNT=$(git rev-list --count HEAD)
+            echo "Commit count: $COMMIT_COUNT"
+            KSU_VERSION=$(expr $COMMIT_COUNT + $BASE_VERSION)
+            echo "Calculated KSUVER: $KSU_VERSION"
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+          else
+            echo "Error: KernelSU directory $KSU_DIR not found!"
+            exit 1
+          fi
           
       - name: Apply Hooks Patches
         run: |
@@ -382,8 +399,12 @@ jobs:
         run: |
           cd "$CONFIG"
 
-          # Set UTS_VERSION with UTS_TIMESTAMP
-          perl -pi -e "s{UTS_VERSION=\"\\\$\(echo \\\$UTS_VERSION \\\$CONFIG_FLAGS \\\$TIMESTAMP \| cut -b -\\\$UTS_LEN\)\"}{UTS_VERSION=\"#1 SMP PREEMPT \${{ env.UTS_TIMESTAMP }}\"}" ./common/scripts/mkcompile_h
+          # Set dynamic UTS_TIMESTAMP
+          UTS_TIMESTAMP=$(date -u "+%a %b %d %H:%M:%S UTC %Y")
+          echo "UTS_TIMESTAMP=$UTS_TIMESTAMP" >> $GITHUB_ENV
+
+          # Modify UTS_VERSION with UTS_TIMESTAMP
+          perl -pi -e 's{UTS_VERSION="\$\(echo \$UTS_VERSION \$CONFIG_FLAGS \$TIMESTAMP \| cut -b -\$UTS_LEN\)"}{UTS_VERSION="#1 SMP PREEMPT '"$UTS_TIMESTAMP"'"}' ./common/scripts/mkcompile_h
 
           # Add custom suffix to setlocalversion
           sed -i '$s|echo "\$res"|echo "\$res-TheFloresto+"|' ./common/scripts/setlocalversion
@@ -392,16 +413,16 @@ jobs:
           if [ -f "build/build.sh" ]; then
             sed -i 's/-dirty//' ./common/scripts/setlocalversion
           else
-            # Set build-timestamp
-            sed -i "s/build-timestamp = \$(or \$(KBUILD_BUILD_TIMESTAMP), \$(build-timestamp-auto))/build-timestamp = \"\${{ env.UTS_TIMESTAMP }}\"/" ./common/init/Makefile
+            # Set build-timestamp with proper escaping
+            sed -i 's/build-timestamp = \$(or \$(KBUILD_BUILD_TIMESTAMP), \$(build-timestamp-auto))/build-timestamp = "'"$UTS_TIMESTAMP"'"/' ./common/init/Makefile
             sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' ./common/BUILD.bazel
             rm -rf ./common/android/abi_gki_protected_exports_*
-            sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
-            sed -E -i "/^CONFIG_LOCALVERSION=/ s/(.*)\"/\\1-TheFloresto+\"/" ./common/arch/arm64/configs/gki_defconfig
+            sed -i 's/-maybe-dirty//' ./build/kernel/kleaf/impl/stamp.bzl
+            sed -i "/^CONFIG_LOCALVERSION=/ s/\"$/\"-TheFloresto+/" ./common/arch/arm64/configs/gki_defconfig
           fi
 
           # Remove check_defconfig
-          sed -i '2s/check_defconfig//' ./common/build.config.gki 
+          sed -i 's/check_defconfig//' ./common/build.config.gki
 
       - name: Build
         run : |
